title: Zhezhu Wen, Ph.D.
description: I teach and research production and operations management. Currently, assistant professor in CalState, Fresno.
logo: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=COhwZxAAAAAJ&citpid=3


theme: jekyll-theme-minimal
