title: Zhezhu Wen, Ph.D.
description: I teach and research production and operations management. Currently, assistant professor in CalState, Fresno.
logo: https://craig.fresnostate.edu/images/faculty-headshots/wen-zhezhu.jpg


theme: jekyll-theme-minimal
