title: Zhezhu Wen, Ph.D.
description: Assistant Professor of Production & Operations Management at Cal State Fresno. Research focuses on production and operations management. Ph.D. in Manufacturing & Technology Management (Management Science), University of Toledo; M.S. in Information Systems, University of Mary Hardin-Baylor.
logo: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=COhwZxAAAAAJ&citpid=3


theme: jekyll-theme-minimal
